### ISSUE TITLE
exit and multiple file-browser

### ISSUE THREAD

**Issue by ghost** [sumitchawla/file-browser#1]
I can not close the server with `CTRL+C`. How can I terminate file-browser ?

How to serve multiple file-browser ?
When I have run file-browser again, I have following error.

```
Please open the link in your browser http://<YOUR-IP>:8088
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/file-browser/index.js:31:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by sumitchawla** [comment]
Ctrl-C should work in most cases.  If you are running it in background then you will have to kill it using kill command.  Which environment are you running on?

**Comment by ghost** [comment]
My system is Ubuntu 14.4 and I have tested again and this time CTRL+C terminate file-browser.

What I want to do is dynamically load the target folder. I have tested below.

I have uninstalled file-browser installed with -g.
Then I have installed file-browser locally and execute with `node index.js` and It works.
Now I can see the file-browser in chrome browser.

I will review your code and modify it to my requirement.

Thanks for your great works.

**Comment by sumitchawla** [comment]
Good to hear that its working fine for you. Do contribute back in case you find something missing.
